"""Change gender column from boolean to enum


Revision ID: 4ce1912cc0db
Revises: 85cf10c882a3
Create Date: 2026-03-12 15:42:15.576742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ce1912cc0db'
down_revision = '85cf10c882a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE gendersenum AS ENUM ('male', 'female', 'other')")
    op.execute("ALTER TABLE students ALTER COLUMN gender TYPE gendersenum USING CASE WHEN gender = true THEN 'male'::gendersenum ELSE 'female'::gendersenum END")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE students ALTER COLUMN gender TYPE boolean USING CASE WHEN gender = 'male' THEN true ELSE false END")
    op.execute("DROP TYPE gendersenum")
    # ### end Alembic commands ###
